### ISSUE TITLE
Bug: You can't call a method the same as a property.

### ISSUE THREAD

**Issue by OdinoCano** [SeyedSaeidDehghani/VoiPy#1]
def start(self) -> tuple or bool:
        print("start_in")
        connect = self.connect()
        if connect:
            self.response.name = "RECEIVE"
            self.response.start()

Exist start() method and start() property

**Comment by SeyedSaeidDehghani** [comment]
#### Hi @OdinoCano,
#### I really appreciate your consideration,
+ **start() method** is used to **Sip class**  for running sip protocol.
+ **self.response** is instance of **ConcreteReceive class** define in **\_\_init__ Sip class**,  so **self.response.start()** is used to start the thread for get **response** from sip protocol. 

So both of them are **classmethod** and they don't interfere with each other.
